version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=Flask
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33077:3306"
    container_name: "mysql"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 6s
      timeout: 4s
      retries: 5

    volumes:
      - mysql_data:/var/lib/mysql

  site:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /site/main.py
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"


volumes:
  mysql_data:
