version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=Flask
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306" # for localhost port 3307 because i already have local mysql
    container_name: "mysql"
    volumes:
      - ./mysql-data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 6s
      timeout: 4s
      retries: 5

  site:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"

